title: GeekMind 
description: >- # this means to ignore newlines until "baseurl:"
  This is where I document things that I learned.
  Expect content about C++, Ruby and Java.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://almsilva.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: almsilva 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

